### ISSUE TITLE
仅添加一行股票代码，保存后显示`暂无监视对象`

### ISSUE THREAD

**Issue by AllinProgram** [mrhuo/StockWatcher#1]
仅添加一行股票代码，保存后显示`暂无监视对象`

**Comment by mrhuo** [comment]
有个定时刷新时间，你看再次打开设置界面看里面有没有这条记录？

**Comment by AllinProgram** [comment]
> 有个定时刷新时间，你看再次打开设置界面看里面有没有这条记录？

 感谢回复，对于这个我有查看，一切正常，但是出现了该问题，对于这个问题我选择了新增多条关注代码，并且正在看源码中。
